### ISSUE TITLE
datetime evaluations

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/filter#9]
Previous to 1.5.0, this expression worked in a filter, all values being datetime.utcnow objects:
{{($simtime - $eventtime) > datetime.timedelta(seconds=20)}}
Currently, this results in the following error:
 Filter condition evaluation failed: TypeError: unsupported operand type(s) for -: 'str' and 'datetime.datetime'

As of today, the working expression looks like:
{{($simtime - datetime.timedelta(seconds=20)) > $eventtime}}

I verified the inputs to the filter were valid datetime objects, and not strings, but was unable to get it pass until using the above working expression.

**Comment by mattdodge** [comment]
This error indicates that `$simtime` is likely a string and not a datetime object. However the fact that your second expression is working is strange if that were the case. 

Regardless, this isn't an issue with the filter block, something is going on with the values you are passing through your signals. Happy to help investigate but am going to close the issue on the block.
